<?php
const OPERATION_TYPE_CREATE = 1;
const OPERATION_TYPE_UPDATE = 2;
const OPERATION_TYPE_DELETE = 3;

const OPERATION_TYPE_NAME_LIST = [
    OPERATION_TYPE_CREATE => "登録",
    OPERATION_TYPE_UPDATE => "更新",
    OPERATION_TYPE_DELETE => "削除",
];
